apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: activator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: activator
subjects:
- kind: ServiceAccount
  name: default
