apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: epp
rules:
- apiGroups:
  - inference.networking.x-k8s.io
  resources:
  - inferenceobjectives
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - inference.networking.x-k8s.io
  - inference.networking.k8s.io
  resources:
  - inferencepools
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - list
