apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferencePool
metadata:
  name: llama3-8b-instruct-epp
spec:
  extensionRef:
    failureMode: FailClose
    group: ""
    kind: Service
    name: llama3-8b-instruct-epp
    portNumber: 9002
  selector:
    llm-d.ai/model: "llama3-8b-instruct"
    llm-d.ai/inferenceServing: "true"
  targetPortNumber: 8000
