apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama3-8b-instruct
spec:
  replicas: 1
  selector:
    matchLabels:
      llm-d.ai/model: "llama3-8b-instruct"
      llm-d.ai/inferenceServing: "true"
  template:
    metadata:
      labels:
        llm-d.ai/model: "llama3-8b-instruct"
        llm-d.ai/inferenceServing: "true"
    spec:
      containers:
      - args:
        - --model
        - meta-llama/Llama-3.1-8B-Instruct
        - --port
        - "8000"
        image: ghcr.io/llm-d/llm-d-inference-sim:v0.5.1
        imagePullPolicy: IfNotPresent
        name: vllm-sim
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
